export const productArray = [
  {
    id: "1",
    name: "The Best Jacket",
    color: "Forrest Green",
    size: "Medium",
    image: "/images/shop/jacket-green.png",
    price: 1500,
  },
  {
    id: "2",
    name: "The Short Jacket",
    color: "Light Grey",
    size: "Medium",
    image: "/images/shop/jacket-grey.png",
    price: 1500,
  },
  {
    id: "3",
    name: "The Long Jacket",
    color: "Sand",
    size: "Medium",
    image: "/images/shop/jacket-beige.png",

    price: 1500,
  },
  {
    id: "4",
    name: "The Best Jacket II",
    color: "Bright Yellow",
    size: "Medium",
    image: "/images/shop/jacket-yellow.png",
    price: 1500,
  },
  {
    id: "5",
    name: "The Short Jacket II",
    color: "Black",
    size: "Medium",
    image: "/images/shop/jacket-black.png",
    price: 1500,
  },
  {
    id: "6",
    name: "The Long Jacket II",
    color: "Blue",
    size: "Medium",
    image: "/images/shop/jacket-blue.png",
    price: 1500,
  },
  {
    id: "7",
    name: "The Best Jacket",
    color: "Forrest Green",
    size: "Medium",
    image: "/images/shop/jacket-green.png",
    price: 1500,
  },
  {
    id: "8",
    name: "The Short Jacket",
    color: "Light Grey",
    size: "Medium",
    image: "/images/shop/jacket-grey.png",
    price: 1500,
  },
  {
    id: "9",
    name: "The Long Jacket",
    color: "Sand",
    size: "Medium",
    image: "/images/shop/jacket-beige.png",
    price: 1500,
  },
  {
    id: "10",
    name: "The Best Jacket II",
    color: "Bright Yellow",
    size: "Medium",
    image: "/images/shop/jacket-yellow.png",
    price: 1500,
  },
  {
    id: "11",
    name: "The Short Jacket II",
    color: "Black",
    size: "Medium",
    image: "/images/shop/jacket-black.png",
    price: 1500,
  },
  {
    id: "12",
    name: "The Long Jacket II",
    color: "Blue",
    size: "Medium",
    image: "/images/shop/jacket-blue.png",
    price: 1500,
  },
];
